# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 0.29.4
package:
  name: sofka
  version: ${{ version }}
source:
- if: linux and x86_64
  then:
  - url: https://github.com/nklmilojevic/sofka/releases/download/v${{ version }}/sofka-v${{
      version }}-x86_64-unknown-linux-gnu.tar.gz
    sha256: 61c8647c7fbfa4dce3df37b0094e7c21e8608c7956992c8e48b8cc9ff4f44232
- if: linux and aarch64
  then:
  - url: https://github.com/nklmilojevic/sofka/releases/download/v${{ version }}/sofka-v${{
      version }}-aarch64-unknown-linux-gnu.tar.gz
    sha256: cbb18a76eb0525fcb2290c9f71e27e0749fb2cf00293172330176403079e0b28
- if: osx and x86_64
  then:
  - url: https://github.com/nklmilojevic/sofka/releases/download/v${{ version }}/sofka-v${{
      version }}-x86_64-apple-darwin.tar.gz
    sha256: 4fa1928e05f5fe15be78da7a872643ce30dc5ecca8e1a356e314ad1719bee6ac
- if: osx and arm64
  then:
  - url: https://github.com/nklmilojevic/sofka/releases/download/v${{ version }}/sofka-v${{
      version }}-aarch64-apple-darwin.tar.gz
    sha256: bf367aa91953faf6141628d4eb91b3ed0044920262676bea55c1e272f8231274
build:
  number: 0
  skip: win
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
    - '**/*'
  script: python -c "import os, shutil, stat, sys; prefix = os.environ.get('PREFIX');
    [exit(1) if not prefix else None]; bin_dir = os.path.join(prefix, 'bin'); binary_name
    = 'sofka'; os.makedirs(bin_dir, exist_ok=True); source_patterns = [binary_name,
    f'./{binary_name}', os.path.join('.', binary_name)]; source_file = next((p for
    p in source_patterns if os.path.isfile(p)), None); [exit(1) if not source_file
    else None]; dest_file = os.path.join(bin_dir, binary_name); shutil.copy2(source_file,
    dest_file); os.chmod(dest_file, os.stat(dest_file).st_mode | stat.S_IEXEC | stat.S_IXUSR
    | stat.S_IXGRP | stat.S_IXOTH)"
requirements:
  build: null
  run: null
tests:
- script:
  - sofka --version
about:
  homepage: https://sofka.rs
  repository: https://github.com/nklmilojevic/sofka
  documentation: https://sofka.rs
  license: Apache-2.0
  summary: A Kubernetes TUI, reimagined in Rust - built on kube-rs and ratatui, async-first
    from the ground up
  description: 'sofka is a terminal UI for Kubernetes, reimagined in Rust. Built on
    kube-rs and ratatui, async-first from the ground up.

    '
extra:
  recipe-maintainers:
  - longredzhong
