# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 0.25.1
package:
  name: sofka
  version: ${{ version }}
source:
- if: linux and x86_64
  then:
  - url: https://github.com/nklmilojevic/sofka/releases/download/v${{ version }}/sofka-v${{
      version }}-x86_64-unknown-linux-gnu.tar.gz
    sha256: 05820f4c2feee362a725b6f25bdaf95709f7d9770de4197a9f7ec867066641ea
- if: linux and aarch64
  then:
  - url: https://github.com/nklmilojevic/sofka/releases/download/v${{ version }}/sofka-v${{
      version }}-aarch64-unknown-linux-gnu.tar.gz
    sha256: e2e4fd62f2779cd9cdea070f1a3244c7dedc1caa894454975051d518fd38d722
- if: osx and x86_64
  then:
  - url: https://github.com/nklmilojevic/sofka/releases/download/v${{ version }}/sofka-v${{
      version }}-x86_64-apple-darwin.tar.gz
    sha256: 2f2320a6bda948f4f09dbff5e750ce8b362048d0568d270532b012c0b7a7ae92
- if: osx and arm64
  then:
  - url: https://github.com/nklmilojevic/sofka/releases/download/v${{ version }}/sofka-v${{
      version }}-aarch64-apple-darwin.tar.gz
    sha256: 09601794547777b6df2e436f8e767e245bbfa05eb823154626075fca835a32be
build:
  number: 0
  skip: win
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
    - '**/*'
  script: python -c "import os, shutil, stat, sys; prefix = os.environ.get('PREFIX');
    [exit(1) if not prefix else None]; bin_dir = os.path.join(prefix, 'bin'); binary_name
    = 'sofka'; os.makedirs(bin_dir, exist_ok=True); source_patterns = [binary_name,
    f'./{binary_name}', os.path.join('.', binary_name)]; source_file = next((p for
    p in source_patterns if os.path.isfile(p)), None); [exit(1) if not source_file
    else None]; dest_file = os.path.join(bin_dir, binary_name); shutil.copy2(source_file,
    dest_file); os.chmod(dest_file, os.stat(dest_file).st_mode | stat.S_IEXEC | stat.S_IXUSR
    | stat.S_IXGRP | stat.S_IXOTH)"
requirements:
  build: null
  run: null
tests:
- script:
  - sofka --version
about:
  homepage: https://sofka.rs
  repository: https://github.com/nklmilojevic/sofka
  documentation: https://sofka.rs
  license: Apache-2.0
  summary: A Kubernetes TUI, reimagined in Rust - built on kube-rs and ratatui, async-first
    from the ground up
  description: 'sofka is a terminal UI for Kubernetes, reimagined in Rust. Built on
    kube-rs and ratatui, async-first from the ground up.

    '
extra:
  recipe-maintainers:
  - longredzhong
