# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 0.28.4
package:
  name: sofka
  version: ${{ version }}
source:
- if: linux and x86_64
  then:
  - url: https://github.com/nklmilojevic/sofka/releases/download/v${{ version }}/sofka-v${{
      version }}-x86_64-unknown-linux-gnu.tar.gz
    sha256: bab2a28cca71b895007bf47eb1227e709b06331ab310eec4dc6c06d985229a27
- if: linux and aarch64
  then:
  - url: https://github.com/nklmilojevic/sofka/releases/download/v${{ version }}/sofka-v${{
      version }}-aarch64-unknown-linux-gnu.tar.gz
    sha256: 847ca034d737b0bd05420126f332a2e5fb04f439a95ec0439e2d092ca3c58319
- if: osx and x86_64
  then:
  - url: https://github.com/nklmilojevic/sofka/releases/download/v${{ version }}/sofka-v${{
      version }}-x86_64-apple-darwin.tar.gz
    sha256: e1e5fb4c7f84a669e98e3dc5a785101cab38cf18b56f5e26147e2fdb1bc9788c
- if: osx and arm64
  then:
  - url: https://github.com/nklmilojevic/sofka/releases/download/v${{ version }}/sofka-v${{
      version }}-aarch64-apple-darwin.tar.gz
    sha256: 4860ccf1e146958687f74c485a2fc970c699575e4d144b204f86d3b624159820
build:
  number: 0
  skip: win
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
    - '**/*'
  script: python -c "import os, shutil, stat, sys; prefix = os.environ.get('PREFIX');
    [exit(1) if not prefix else None]; bin_dir = os.path.join(prefix, 'bin'); binary_name
    = 'sofka'; os.makedirs(bin_dir, exist_ok=True); source_patterns = [binary_name,
    f'./{binary_name}', os.path.join('.', binary_name)]; source_file = next((p for
    p in source_patterns if os.path.isfile(p)), None); [exit(1) if not source_file
    else None]; dest_file = os.path.join(bin_dir, binary_name); shutil.copy2(source_file,
    dest_file); os.chmod(dest_file, os.stat(dest_file).st_mode | stat.S_IEXEC | stat.S_IXUSR
    | stat.S_IXGRP | stat.S_IXOTH)"
requirements:
  build: null
  run: null
tests:
- script:
  - sofka --version
about:
  homepage: https://sofka.rs
  repository: https://github.com/nklmilojevic/sofka
  documentation: https://sofka.rs
  license: Apache-2.0
  summary: A Kubernetes TUI, reimagined in Rust - built on kube-rs and ratatui, async-first
    from the ground up
  description: 'sofka is a terminal UI for Kubernetes, reimagined in Rust. Built on
    kube-rs and ratatui, async-first from the ground up.

    '
extra:
  recipe-maintainers:
  - longredzhong
