# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 1.1.60
package:
  name: opencode
  version: ${{ version }}
source:
- if: linux and x86_64
  then:
  - url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-linux-x64.tar.gz
    sha256: 138eb158e699bd3879273b2a679f98d7a5d8d3d437ba3f5ac9e2fa7ea2388604
- if: osx and x86_64
  then:
  - url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-darwin-x64.zip
    sha256: 68ab470ed9c59c5d80fa577c7ca13a095d99b5b424c2fe6ef8281a45c13da2c6
- if: osx and arm64
  then:
  - url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-darwin-arm64.zip
    sha256: dd9c487409d23302f6ec52042685a513207d8686b36e89a34388536ca6cf9409
- if: win and x86_64
  then:
  - url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-windows-x64.zip
    sha256: aafa505bd31aa12afe80ca3031a323cfd9d0943f0671ab96dbe797e534a7b554
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
    - '**/*'
  script: 'python -c "import os, shutil, stat, sys; prefix = os.environ.get(''PREFIX'');
    [exit(1) if not prefix else None]; bin_dir = os.path.join(prefix, ''bin'') if
    (sys.platform.startswith(''linux'') or sys.platform == ''darwin'') else os.path.join(prefix,
    ''Scripts''); binary_name = ''opencode'' if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else ''opencode.exe''; os.makedirs(bin_dir, exist_ok=True);
    source_patterns = [binary_name, f''./{binary_name}'', os.path.join(''.'', binary_name)];
    source_file = next((p for p in source_patterns if os.path.isfile(p)), None); [exit(1)
    if not source_file else None]; dest_file = os.path.join(bin_dir, binary_name);
    shutil.copy2(source_file, dest_file); (lambda: os.chmod(dest_file, os.stat(dest_file).st_mode
    | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH) if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else None)()"

    '
requirements:
  build: null
  run: null
tests:
- script:
  - opencode --version
about:
  homepage: https://opencode.ai
  license: Apache-2.0
  summary: OpenCode - AI coding agent for your terminal
  description: 'OpenCode is an open-source AI coding agent that helps you write, edit,
    and debug code

    directly from your terminal. It provides intelligent code completion, refactoring

    suggestions, and automated coding assistance powered by advanced AI models.

    '
  repository: https://github.com/anomalyco/opencode
  documentation: https://opencode.ai/docs
extra:
  recipe-maintainers:
  - longredzhong
