# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 1.2.11
package:
  name: opencode
  version: ${{ version }}
source:
- if: linux and x86_64
  then:
  - url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-linux-x64.tar.gz
    sha256: ace0bfc38ca4a6f74eb24a53ebd1ae383c81878b5a30eab8027c68a0a15b1b45
- if: linux and arm64
  then:
  - url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-linux-arm64.tar.gz
    sha256: 2fc9fbdaafe93d7b32085f604f90b79b5aaa2559478dc188979ac69d5e0eed55
- if: osx and x86_64
  then:
  - url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-darwin-x64.zip
    sha256: f7dbed021ee60fd5d3e4bed5c0361b92c6226b7010bcfe3a7258db462806b86e
- if: osx and arm64
  then:
  - url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-darwin-arm64.zip
    sha256: 1b83133bc12b60a82abff10fb7d1c0c6576b49c6c4a39890b346ff90f5634bde
- if: win and x86_64
  then:
  - url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-windows-x64.zip
    sha256: 721d6954489ce707b7680272a279eacd74766d94a62fb9bf53f0b2cb6cbd59f7
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
    - '**/*'
  script: 'python -c "import os, shutil, stat, sys; prefix = os.environ.get(''PREFIX'');
    [exit(1) if not prefix else None]; bin_dir = os.path.join(prefix, ''bin'') if
    (sys.platform.startswith(''linux'') or sys.platform == ''darwin'') else os.path.join(prefix,
    ''Scripts''); binary_name = ''opencode'' if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else ''opencode.exe''; os.makedirs(bin_dir, exist_ok=True);
    source_patterns = [binary_name, f''./{binary_name}'', os.path.join(''.'', binary_name)];
    source_file = next((p for p in source_patterns if os.path.isfile(p)), None); [exit(1)
    if not source_file else None]; dest_file = os.path.join(bin_dir, binary_name);
    shutil.copy2(source_file, dest_file); (lambda: os.chmod(dest_file, os.stat(dest_file).st_mode
    | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH) if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else None)()"

    '
requirements:
  build: null
  run: null
tests:
- script:
  - opencode --version
about:
  homepage: https://opencode.ai
  license: Apache-2.0
  summary: OpenCode - AI coding agent for your terminal
  description: 'OpenCode is an open-source AI coding agent that helps you write, edit,
    and debug code

    directly from your terminal. It provides intelligent code completion, refactoring

    suggestions, and automated coding assistance powered by advanced AI models.

    '
  repository: https://github.com/anomalyco/opencode
  documentation: https://opencode.ai/docs
extra:
  recipe-maintainers:
  - longredzhong
