# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 1.1.63
package:
  name: opencode
  version: ${{ version }}
source:
- if: linux and x86_64
  then:
  - url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-linux-x64.tar.gz
    sha256: 4c64c6852f40f7324eea32d0553cd1d28c4ce997e1aa0e3807920af18bf8b83a
- if: osx and x86_64
  then:
  - url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-darwin-x64.zip
    sha256: 17798f99978fa80424c523248444edbcdf030f321601f43342942ca7a42f73a6
- if: osx and arm64
  then:
  - url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-darwin-arm64.zip
    sha256: 53f12fe136348716e15561b74eac84896128dc86cda41e286aba8fbc7ea54943
- if: win and x86_64
  then:
  - url: https://github.com/anomalyco/opencode/releases/download/v${{ version }}/opencode-windows-x64.zip
    sha256: 82819fc0f42e6caa911d1f28cd85148ef19dbf918a8dad6d507f5ec333b4e7ef
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
    - '**/*'
  script: 'python -c "import os, shutil, stat, sys; prefix = os.environ.get(''PREFIX'');
    [exit(1) if not prefix else None]; bin_dir = os.path.join(prefix, ''bin'') if
    (sys.platform.startswith(''linux'') or sys.platform == ''darwin'') else os.path.join(prefix,
    ''Scripts''); binary_name = ''opencode'' if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else ''opencode.exe''; os.makedirs(bin_dir, exist_ok=True);
    source_patterns = [binary_name, f''./{binary_name}'', os.path.join(''.'', binary_name)];
    source_file = next((p for p in source_patterns if os.path.isfile(p)), None); [exit(1)
    if not source_file else None]; dest_file = os.path.join(bin_dir, binary_name);
    shutil.copy2(source_file, dest_file); (lambda: os.chmod(dest_file, os.stat(dest_file).st_mode
    | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH) if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else None)()"

    '
requirements:
  build: null
  run: null
tests:
- script:
  - opencode --version
about:
  homepage: https://opencode.ai
  license: Apache-2.0
  summary: OpenCode - AI coding agent for your terminal
  description: 'OpenCode is an open-source AI coding agent that helps you write, edit,
    and debug code

    directly from your terminal. It provides intelligent code completion, refactoring

    suggestions, and automated coding assistance powered by advanced AI models.

    '
  repository: https://github.com/anomalyco/opencode
  documentation: https://opencode.ai/docs
extra:
  recipe-maintainers:
  - longredzhong
