# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 0.78.19
package:
  name: hatchet-cli
  version: ${{ version }}
source:
- if: linux and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Linux_x86_64.tar.gz
    sha256: c03af0dca4fac411c001010b16a4da9f2ec7a273423467b4cefbd7a45e303bfd
- if: osx and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Darwin_x86_64.tar.gz
    sha256: a8835740ecdfcb396c9f8e8042afda1ac03d393941f6566c239d1909a05918c1
- if: osx and arm64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Darwin_arm64.tar.gz
    sha256: 257c3182b93d0786ae132e10e7704f25414e344608235794626ffe0a2b835244
- if: win and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Windows_x86_64.zip
    sha256: a4a5180bce88826c1afc8c1bdb68dbede1ecea4f3215c70e3ee17e9b5e909eed
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
    - '**/*'
  script: 'python -c "import os, shutil, stat, sys; prefix = os.environ.get(''PREFIX'');
    [exit(1) if not prefix else None]; bin_dir = os.path.join(prefix, ''bin'') if
    (sys.platform.startswith(''linux'') or sys.platform == ''darwin'') else os.path.join(prefix,
    ''Scripts''); binary_name = ''hatchet'' if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else ''hatchet.exe''; os.makedirs(bin_dir, exist_ok=True);
    source_patterns = [binary_name, f''./{binary_name}'', os.path.join(''.'', binary_name)];
    source_file = next((p for p in source_patterns if os.path.isfile(p)), None); [exit(1)
    if not source_file else None]; dest_file = os.path.join(bin_dir, binary_name);
    shutil.copy2(source_file, dest_file); (lambda: os.chmod(dest_file, os.stat(dest_file).st_mode
    | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH) if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else None)()"

    '
requirements:
  build: null
  run: null
tests:
- script:
  - hatchet --version
about:
  homepage: https://hatchet.run
  license: MIT
  summary: The Hatchet CLI for managing workflows and background tasks
  description: 'Hatchet is an open-source platform for running background tasks and
    durable workflows at scale.

    The CLI allows you to manage workers, workflows, and operate local or remote Hatchet
    environments.

    '
  repository: https://github.com/hatchet-dev/hatchet
  documentation: https://docs.hatchet.run
extra:
  recipe-maintainers:
  - longredzhong
