context:
  version: "0.77.36"

package:
  name: hatchet-cli
  version: ${{ version }}

source:
  - if: linux and x86_64
    then:
      - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{ version }}_Linux_x86_64.tar.gz
        sha256: f6b5ac42b2bedd36e6958872fbe111ae05060fd14ff7cbd4ade42c6aa6f8d340
  - if: osx and x86_64
    then:
      - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{ version }}_Darwin_x86_64.tar.gz
        sha256: 3c6b636641874edb4b48e8443e369bae88ecf36a959a37ef8bffda1ef9f59746
  - if: osx and arm64
    then:
      - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{ version }}_Darwin_arm64.tar.gz
        sha256: a028e05c31085ce6ae8a022851f915e84537cda8d8e5a75c234c5b3909b0213b

build:
  number: 0
  script:
    - mkdir -p $PREFIX/bin # [unix]
    - cp hatchet $PREFIX/bin/ # [unix]
    - chmod +x $PREFIX/bin/hatchet # [unix]

requirements:
  build:
  run:

tests:
  - script:
      - hatchet --version

about:
  homepage: https://hatchet.run
  license: MIT
  summary: The Hatchet CLI for managing workflows and background tasks
  description: |
    Hatchet is an open-source platform for running background tasks and durable workflows at scale.
    The CLI allows you to manage workers, workflows, and operate local or remote Hatchet environments.
  repository: https://github.com/hatchet-dev/hatchet
  documentation: https://docs.hatchet.run

extra:
  recipe-maintainers:
    - longredzhong
