# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 0.78.5
package:
  name: hatchet-cli
  version: ${{ version }}
source:
- if: linux and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Linux_x86_64.tar.gz
    sha256: a6f2baf0d4512da1e95f6cec01d0ae71d635ca6b737896233bbc8691455cc062
- if: osx and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Darwin_x86_64.tar.gz
    sha256: 112ec92559f8abb7c63df6893d0e4a38c07174d38a3aa57cd9d1a0a69a6c8e2a
- if: osx and arm64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Darwin_arm64.tar.gz
    sha256: 2d9cf306ed24178732b688542c5cb3ef43c2b671f683b3bfef51a73bf653a33e
- if: win and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Windows_x86_64.zip
    sha256: ec3dac89de7f748d54c72a886dd663ead975b8992d981db0afd770de83ccffc6
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
    - '**/*'
  script: 'python -c "import os, shutil, stat, sys; prefix = os.environ.get(''PREFIX'');
    [exit(1) if not prefix else None]; bin_dir = os.path.join(prefix, ''bin'') if
    (sys.platform.startswith(''linux'') or sys.platform == ''darwin'') else os.path.join(prefix,
    ''Scripts''); binary_name = ''hatchet'' if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else ''hatchet.exe''; os.makedirs(bin_dir, exist_ok=True);
    source_patterns = [binary_name, f''./{binary_name}'', os.path.join(''.'', binary_name)];
    source_file = next((p for p in source_patterns if os.path.isfile(p)), None); [exit(1)
    if not source_file else None]; dest_file = os.path.join(bin_dir, binary_name);
    shutil.copy2(source_file, dest_file); (lambda: os.chmod(dest_file, os.stat(dest_file).st_mode
    | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH) if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else None)()"

    '
requirements:
  build: null
  run: null
tests:
- script:
  - hatchet --version
about:
  homepage: https://hatchet.run
  license: MIT
  summary: The Hatchet CLI for managing workflows and background tasks
  description: 'Hatchet is an open-source platform for running background tasks and
    durable workflows at scale.

    The CLI allows you to manage workers, workflows, and operate local or remote Hatchet
    environments.

    '
  repository: https://github.com/hatchet-dev/hatchet
  documentation: https://docs.hatchet.run
extra:
  recipe-maintainers:
  - longredzhong
