# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 0.78.29
package:
  name: hatchet-cli
  version: ${{ version }}
source:
- if: linux and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Linux_x86_64.tar.gz
    sha256: ccc227ad4dccb565f51b5ba6c354a22f48d041796fb8a48da91128f8757706c9
- if: linux and arm64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Linux_arm64.tar.gz
    sha256: ef33abf34bad6800d43284080c5f282b662d1f737dd9123891edd29f7651105d
- if: osx and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Darwin_x86_64.tar.gz
    sha256: 370170b616555f5f00573d41605b32691f294b49ac7339b4bb4ee09ea09e6e89
- if: osx and arm64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Darwin_arm64.tar.gz
    sha256: 5c1d0b88221aa288656b23f9f708431f8ea952c1480f3138864e47325de5bcc8
- if: win and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Windows_x86_64.zip
    sha256: 3e189bdbfac71cedfbf67ddf282989cd3a0f56b5d2c36e6bc5ef349f7f88cf0b
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
    - '**/*'
  script: 'python -c "import os, shutil, stat, sys; prefix = os.environ.get(''PREFIX'');
    [exit(1) if not prefix else None]; bin_dir = os.path.join(prefix, ''bin'') if
    (sys.platform.startswith(''linux'') or sys.platform == ''darwin'') else os.path.join(prefix,
    ''Scripts''); binary_name = ''hatchet'' if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else ''hatchet.exe''; os.makedirs(bin_dir, exist_ok=True);
    source_patterns = [binary_name, f''./{binary_name}'', os.path.join(''.'', binary_name)];
    source_file = next((p for p in source_patterns if os.path.isfile(p)), None); [exit(1)
    if not source_file else None]; dest_file = os.path.join(bin_dir, binary_name);
    shutil.copy2(source_file, dest_file); (lambda: os.chmod(dest_file, os.stat(dest_file).st_mode
    | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH) if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else None)()"

    '
requirements:
  build: null
  run: null
tests:
- script:
  - hatchet --version
about:
  homepage: https://hatchet.run
  license: MIT
  summary: The Hatchet CLI for managing workflows and background tasks
  description: 'Hatchet is an open-source platform for running background tasks and
    durable workflows at scale.

    The CLI allows you to manage workers, workflows, and operate local or remote Hatchet
    environments.

    '
  repository: https://github.com/hatchet-dev/hatchet
  documentation: https://docs.hatchet.run
extra:
  recipe-maintainers:
  - longredzhong
