# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 0.79.3
package:
  name: hatchet-cli
  version: ${{ version }}
source:
- if: linux and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Linux_x86_64.tar.gz
    sha256: 001b04bc394345b7f359604a58d3b6b4e6ccfc9aaacf52a841bfbb2e24e958b3
- if: linux and arm64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Linux_arm64.tar.gz
    sha256: 31515f97c27f2782ff65e9c613762c973b40dbcd5559e5b6a51a9784a3c45897
- if: osx and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Darwin_x86_64.tar.gz
    sha256: 01f9824890493a6848a2de3c1b5664f195f43fed9032cc1646868a5adb667616
- if: osx and arm64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Darwin_arm64.tar.gz
    sha256: 9d497936120c10ce6918fd1a6e12b5021842d6497ecb90e49225cc841532a871
- if: win and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Windows_x86_64.zip
    sha256: 387c133677e3f9219ea592fe968e26b9a750945dd6f28b9617c00d1c47e98c2e
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
    - '**/*'
  script: 'python -c "import os, shutil, stat, sys; prefix = os.environ.get(''PREFIX'');
    [exit(1) if not prefix else None]; bin_dir = os.path.join(prefix, ''bin'') if
    (sys.platform.startswith(''linux'') or sys.platform == ''darwin'') else os.path.join(prefix,
    ''Scripts''); binary_name = ''hatchet'' if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else ''hatchet.exe''; os.makedirs(bin_dir, exist_ok=True);
    source_patterns = [binary_name, f''./{binary_name}'', os.path.join(''.'', binary_name)];
    source_file = next((p for p in source_patterns if os.path.isfile(p)), None); [exit(1)
    if not source_file else None]; dest_file = os.path.join(bin_dir, binary_name);
    shutil.copy2(source_file, dest_file); (lambda: os.chmod(dest_file, os.stat(dest_file).st_mode
    | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH) if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else None)()"

    '
requirements:
  build: null
  run: null
tests:
- script:
  - hatchet --version
about:
  homepage: https://hatchet.run
  license: MIT
  summary: The Hatchet CLI for managing workflows and background tasks
  description: 'Hatchet is an open-source platform for running background tasks and
    durable workflows at scale.

    The CLI allows you to manage workers, workflows, and operate local or remote Hatchet
    environments.

    '
  repository: https://github.com/hatchet-dev/hatchet
  documentation: https://docs.hatchet.run
extra:
  recipe-maintainers:
  - longredzhong
