# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 0.79.0
package:
  name: hatchet-cli
  version: ${{ version }}
source:
- if: linux and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Linux_x86_64.tar.gz
    sha256: bbef8a434e0401c8170698009d7e569aa0cced31a8c7edd928febef397ca34ee
- if: linux and arm64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Linux_arm64.tar.gz
    sha256: a0ad74cae8b2169f4e8b54c099fa543f3c8cbc22b3340538700be7ee9660275c
- if: osx and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Darwin_x86_64.tar.gz
    sha256: 9f4d0b8902cf9b2b74986e58779a58fbed046e8b1feb234e8beba0505e63095f
- if: osx and arm64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Darwin_arm64.tar.gz
    sha256: 21e3786b4aef1868f51560e0ff1640e9068e3fc6cb791363437728ef5c302d8c
- if: win and x86_64
  then:
  - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{
      version }}_Windows_x86_64.zip
    sha256: 9e9fd893bcf9ddafcba331359a60483a0c35d28860e831856e1ae5a42cabc739
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
    - '**/*'
  script: 'python -c "import os, shutil, stat, sys; prefix = os.environ.get(''PREFIX'');
    [exit(1) if not prefix else None]; bin_dir = os.path.join(prefix, ''bin'') if
    (sys.platform.startswith(''linux'') or sys.platform == ''darwin'') else os.path.join(prefix,
    ''Scripts''); binary_name = ''hatchet'' if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else ''hatchet.exe''; os.makedirs(bin_dir, exist_ok=True);
    source_patterns = [binary_name, f''./{binary_name}'', os.path.join(''.'', binary_name)];
    source_file = next((p for p in source_patterns if os.path.isfile(p)), None); [exit(1)
    if not source_file else None]; dest_file = os.path.join(bin_dir, binary_name);
    shutil.copy2(source_file, dest_file); (lambda: os.chmod(dest_file, os.stat(dest_file).st_mode
    | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH) if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else None)()"

    '
requirements:
  build: null
  run: null
tests:
- script:
  - hatchet --version
about:
  homepage: https://hatchet.run
  license: MIT
  summary: The Hatchet CLI for managing workflows and background tasks
  description: 'Hatchet is an open-source platform for running background tasks and
    durable workflows at scale.

    The CLI allows you to manage workers, workflows, and operate local or remote Hatchet
    environments.

    '
  repository: https://github.com/hatchet-dev/hatchet
  documentation: https://docs.hatchet.run
extra:
  recipe-maintainers:
  - longredzhong
