context:
  version: "0.77.36"

package:
  name: hatchet-cli
  version: ${{ version }}

# Note: sha256 checksums are omitted for convenience in this personal forge.
# For production use, actual checksums should be specified for security.
source:
  - if: linux and x86_64
    then:
      - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{ version }}_Linux_x86_64.tar.gz
  - if: osx and x86_64
    then:
      - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{ version }}_Darwin_x86_64.tar.gz
  - if: osx and arm64
    then:
      - url: https://github.com/hatchet-dev/hatchet/releases/download/v${{ version }}/hatchet_${{ version }}_Darwin_arm64.tar.gz

build:
  number: 0
  script:
    - mkdir -p $PREFIX/bin # [unix]
    - cp hatchet $PREFIX/bin/ # [unix]
    - chmod +x $PREFIX/bin/hatchet # [unix]

requirements:
  build:
  run:

tests:
  - script:
      - hatchet --version

about:
  homepage: https://hatchet.run
  license: MIT
  summary: The Hatchet CLI for managing workflows and background tasks
  description: |
    Hatchet is an open-source platform for running background tasks and durable workflows at scale.
    The CLI allows you to manage workers, workflows, and operate local or remote Hatchet environments.
  repository: https://github.com/hatchet-dev/hatchet
  documentation: https://docs.hatchet.run

extra:
  recipe-maintainers:
    - longredzhong
