# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 0.0.412
package:
  name: copilot-cli
  version: ${{ version }}
source:
- if: linux and x86_64
  then:
  - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-linux-x64.tar.gz
    sha256: 7fdcef0e1cdcfbc8bc88c7efc621d6562b130be56a3e80555617a8872b92335b
- if: linux and arm64
  then:
  - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-linux-arm64.tar.gz
    sha256: f5b54be87cb55cb75016e8909afd411fd2fd729f502fcac6b2a6972fdfb29b9a
- if: osx and x86_64
  then:
  - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-darwin-x64.tar.gz
    sha256: 587b80744ac99e73d8db076ebf840f8dda40b0af24dcb50077b00d51e75a7193
- if: osx and arm64
  then:
  - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-darwin-arm64.tar.gz
    sha256: d706f64a26630863d57e64e78a4048c1f85b7df190f0762237221199032ff2da
- if: win and x86_64
  then:
  - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-win32-x64.zip
    sha256: 1175635e3a90361fd7c39fdf8649e217b9c8d74d2e05f020b82dc1e10eae18b1
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
    - '**/*'
  script: 'python -c "import os, shutil, stat, sys; prefix = os.environ.get(''PREFIX'');
    [exit(1) if not prefix else None]; bin_dir = os.path.join(prefix, ''bin'') if
    (sys.platform.startswith(''linux'') or sys.platform == ''darwin'') else os.path.join(prefix,
    ''Scripts''); binary_name = ''copilot'' if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else ''copilot.exe''; os.makedirs(bin_dir, exist_ok=True);
    source_patterns = [binary_name, f''./{binary_name}'', os.path.join(''.'', binary_name)];
    source_file = next((p for p in source_patterns if os.path.isfile(p)), None); [exit(1)
    if not source_file else None]; dest_file = os.path.join(bin_dir, binary_name);
    shutil.copy2(source_file, dest_file); (lambda: os.chmod(dest_file, os.stat(dest_file).st_mode
    | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH) if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else None)()"

    '
requirements:
  build: null
  run: null
tests:
- script:
  - copilot --version
about:
  homepage: https://github.com/github/copilot-cli
  repository: https://github.com/github/copilot-cli
  documentation: https://docs.github.com/en/copilot/concepts/agents/about-copilot-cli
  license: MIT
  summary: GitHub Copilot CLI - Command-line interface for GitHub Copilot
  description: 'GitHub Copilot CLI is a command-line interface for GitHub Copilot
    that provides access to Copilot''s capabilities from your terminal.

    '
