# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 0.0.400
package:
  name: copilot-cli
  version: ${{ version }}
source:
  - if: linux and x86_64
    then:
      - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-linux-x64.tar.gz
        sha256: e97afcbaad69d03f2d68ec8f4294a9a9b14b34b578e49785fff3deb0c0eab1bf
  - if: osx and x86_64
    then:
      - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-darwin-x64.tar.gz
        sha256: 21ac2624a3f4e00efab8bf6f21f5e9f73647e132a17cffe2c9e57c2090119245
  - if: osx and arm64
    then:
      - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-darwin-arm64.tar.gz
        sha256: 899e6509092ab92c8c6d099fdc17dda11050947f1052219d47569115c5d865c0
  - if: win and x86_64
    then:
      - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-win32-x64.zip
        sha256: 02fc89afbd608c70c98e5c0e2f3db8bec5139d8f103e3f42c1a83dd7a204185c
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
      - "**/*"
  script: |
    python -c "import os, shutil, stat, sys; prefix = os.environ.get('PREFIX'); [exit(1) if not prefix else None]; bin_dir = os.path.join(prefix, 'bin') if (sys.platform.startswith('linux') or sys.platform == 'darwin') else os.path.join(prefix, 'Scripts'); binary_name = 'copilot' if (sys.platform.startswith('linux') or sys.platform == 'darwin') else 'copilot.exe'; os.makedirs(bin_dir, exist_ok=True); source_patterns = [binary_name, f'./{binary_name}', os.path.join('.', binary_name)]; source_file = next((p for p in source_patterns if os.path.isfile(p)), None); [exit(1) if not source_file else None]; dest_file = os.path.join(bin_dir, binary_name); shutil.copy2(source_file, dest_file); (lambda: os.chmod(dest_file, os.stat(dest_file).st_mode | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH) if (sys.platform.startswith('linux') or sys.platform == 'darwin') else None)()"
requirements:
  build: null
  run: null
tests:
  - script:
      - copilot --version
about:
  homepage: https://github.com/github/copilot-cli
  license: MIT
  summary: GitHub Copilot CLI - Command-line interface for GitHub Copilot
  description:
    "GitHub Copilot CLI is a command-line interface for GitHub Copilot
    that provides access to Copilot's capabilities from your terminal.

    "
