# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 0.0.400
package:
  name: copilot-cli
  version: ${{ version }}
source:
  - if: linux and x86_64
    then:
      - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-linux-x64.tar.gz
        sha256: e97afcbaad69d03f2d68ec8f4294a9a9b14b34b578e49785fff3deb0c0eab1bf
  - if: osx and x86_64
    then:
      - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-darwin-x64.tar.gz
        sha256: 21ac2624a3f4e00efab8bf6f21f5e9f73647e132a17cffe2c9e57c2090119245
  - if: osx and arm64
    then:
      - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-darwin-arm64.tar.gz
        sha256: 899e6509092ab92c8c6d099fdc17dda11050947f1052219d47569115c5d865c0
  - if: win and x86_64
    then:
      - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-win32-x64.zip
        sha256: 02fc89afbd608c70c98e5c0e2f3db8bec5139d8f103e3f42c1a83dd7a204185c
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
      - "**/*"
  script: |
    python -c "
    import os
    import shutil
    import glob
    import sys

    prefix = os.environ.get('PREFIX')
    if not prefix:
        raise RuntimeError('PREFIX environment variable not set')

    # Determine platform and set appropriate binary path
    if sys.platform.startswith('linux') or sys.platform == 'darwin':
        bin_dir = os.path.join(prefix, 'bin')
        binary_name = 'copilot'
    else:  # Windows
        bin_dir = os.path.join(prefix, 'Scripts')
        binary_name = 'copilot.exe'

    # Create bin directory
    os.makedirs(bin_dir, exist_ok=True)

    # Find and copy the binary
    source_patterns = [binary_name, f'./{binary_name}', os.path.join('.', binary_name)]
    source_file = None

    for pattern in source_patterns:
        if os.path.isfile(pattern):
            source_file = pattern
            break

    if not source_file:
        raise RuntimeError(f'Binary {binary_name} not found in current directory')

    dest_file = os.path.join(bin_dir, binary_name)
    shutil.copy2(source_file, dest_file)

    # Make executable on Unix systems
    if sys.platform.startswith('linux') or sys.platform == 'darwin':
        import stat
        st = os.stat(dest_file)
        os.chmod(dest_file, st.st_mode | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f'Successfully installed {binary_name} to {dest_file}')
    "
requirements:
  build: null
  run: null
tests:
  - script:
      - copilot --version
about:
  homepage: https://github.com/github/copilot-cli
  license: MIT
  summary: GitHub Copilot CLI - Command-line interface for GitHub Copilot
  description:
    "GitHub Copilot CLI is a command-line interface for GitHub Copilot
    that provides access to Copilot's capabilities from your terminal.

    "
