# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 0.0.420
package:
  name: copilot-cli
  version: ${{ version }}
source:
- if: linux and x86_64
  then:
  - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-linux-x64.tar.gz
    sha256: 344f89ee1e619c9ffcb072381b7e53c2f305053008b55584dc5846d003c167b9
- if: linux and aarch64
  then:
  - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-linux-arm64.tar.gz
    sha256: 60afebcf47644db1cedd4bbe2be9fc18e6ffb4bc394f570a7896b7a8fd889f63
- if: osx and x86_64
  then:
  - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-darwin-x64.tar.gz
    sha256: cd47e1d5287f724be05acfd8564a4628bf6f622dde8156f8b269e1641409989b
- if: osx and arm64
  then:
  - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-darwin-arm64.tar.gz
    sha256: 8216312d266329ea0b1440cc2e685c66b6a26977cfa3d02b0388d6051f3fb6ab
- if: win and x86_64
  then:
  - url: https://github.com/github/copilot-cli/releases/download/v${{ version }}/copilot-win32-x64.zip
    sha256: cd34b0565fa2ad75f8fa0b697cd1cc07627aa6c61df6442106c37b2e78de6e09
build:
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist:
    - '**/*'
  script: 'python -c "import os, shutil, stat, sys; prefix = os.environ.get(''PREFIX'');
    [exit(1) if not prefix else None]; bin_dir = os.path.join(prefix, ''bin'') if
    (sys.platform.startswith(''linux'') or sys.platform == ''darwin'') else os.path.join(prefix,
    ''Scripts''); binary_name = ''copilot'' if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else ''copilot.exe''; os.makedirs(bin_dir, exist_ok=True);
    source_patterns = [binary_name, f''./{binary_name}'', os.path.join(''.'', binary_name)];
    source_file = next((p for p in source_patterns if os.path.isfile(p)), None); [exit(1)
    if not source_file else None]; dest_file = os.path.join(bin_dir, binary_name);
    shutil.copy2(source_file, dest_file); (lambda: os.chmod(dest_file, os.stat(dest_file).st_mode
    | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH) if (sys.platform.startswith(''linux'')
    or sys.platform == ''darwin'') else None)()"

    '
requirements:
  build: null
  run: null
tests:
- script:
  - copilot --version
about:
  homepage: https://github.com/github/copilot-cli
  repository: https://github.com/github/copilot-cli
  documentation: https://docs.github.com/en/copilot/concepts/agents/about-copilot-cli
  license: MIT
  summary: GitHub Copilot CLI - Command-line interface for GitHub Copilot
  description: 'GitHub Copilot CLI is a command-line interface for GitHub Copilot
    that provides access to Copilot''s capabilities from your terminal.

    '
