# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: 0.29.1
package:
  name: gemini-cli
  version: ${{ version }}
source:
- url: https://github.com/google-gemini/gemini-cli/releases/download/v${{ version
    }}/gemini.js
  sha256: a56a2c96784d07b9a7b9db581eb5daefe3ee2e49b7472dfc754796ce18b1b30b
build:
  number: 0
  noarch: generic
  script: "python - <<'PY'\nimport os, shutil\n\nprefix = os.environ.get('PREFIX')\n\
    bin_dir = os.path.join(prefix, 'bin')\nos.makedirs(bin_dir, exist_ok=True)\nshutil.copy2('gemini.js',\
    \ os.path.join(bin_dir, 'gemini.js'))\n\nwrapper = os.path.join(bin_dir, 'gemini')\n\
    with open(wrapper, 'w') as f:\n    f.write('#!/bin/sh\\nexec node \"$(dirname\
    \ \"$0\")/gemini.js\" \"$@\"\\n')\nos.chmod(wrapper, 0o755)\n\nPY\n"
requirements:
  run:
  - nodejs >=18
tests:
- script:
  - gemini --version
about:
  homepage: https://google-gemini.github.io/gemini-cli/
  repository: https://github.com/google-gemini/gemini-cli
  documentation: https://google-gemini.github.io/gemini-cli/docs/
  license: MIT
  summary: Google Gemini CLI - Command-line interface for Google Gemini
  description: "Gemini CLI is a command-line interface for Google Gemini that provides\
    \ access \nto Gemini's AI capabilities from your terminal. It enables you to interact\
    \ with \nGoogle's Gemini models for various tasks including code generation, chat,\
    \ and more.\n"
extra:
  recipe-maintainers:
  - longredzhong
